# Generated by Django 5.2.6 on 2025-09-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
