# Generated by Django 5.2.6 on 2025-09-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_rename_created_on_note_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
