# Generated by Django 5.2.6 on 2025-09-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_rename_created_on_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
