# Generated by Django 5.2.6 on 2025-09-17 08:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0006_alter_user_user_id_notemodel_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='note_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
