# Generated by Django 5.2.6 on 2025-09-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0008_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemodel',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
